# Generated by Django 2.0.6 on 2018-06-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurette',
            name='img_url',
            field=models.CharField(default='https://github.com/juanjoneri/juanjoneri.github.io/blob/master/img/500_500.png', max_length=64),
            preserve_default=False,
        ),
    ]
