# Generated by Django 2.0.6 on 2018-06-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='button_icon',
            field=models.CharField(max_length=32),
        ),
    ]
