# Generated by Django 2.0.6 on 2018-06-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='icon',
            field=models.CharField(default='fas fa-sun', max_length=32),
        ),
    ]
