# Generated by Django 2.0.3 on 2018-08-20 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_visit_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
