# Generated by Django 2.0.6 on 2018-06-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_featurette_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurette',
            name='button',
            field=models.CharField(default='Button', max_length=8),
            preserve_default=False,
        ),
    ]
