# Generated by Django 2.0.6 on 2018-06-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_featurette_button'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featurette',
            old_name='img_url',
            new_name='img',
        ),
    ]
