
SELECT ID, "ROOT" FROM TREE WHERE P_ID IS NULL
UNION
SELECT DISTINCT TREE1.ID, "INNER" FROM TREE TREE1 JOIN TREE TREE2 ON TREE2.P_ID = TREE1.ID WHERE TREE1.P_ID IS NOT NULL
UNION
SELECT TREE1.ID, "LEAF" FROM TREE TREE1 LEFT JOIN TREE TREE2 ON TREE1.ID = TREE2.P_ID WHERE TREE2.P_ID IS NULL
ORDER BY ID;
